# Generated by Django 3.1 on 2023-06-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='google_account_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(verbose_name='信箱')),
            ],
        ),
        migrations.CreateModel(
            name='google_account_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(verbose_name='信箱')),
                ('password', models.TextField(verbose_name='密碼')),
                ('bakemail', models.TextField(verbose_name='備用信箱')),
                ('phone', models.TextField(verbose_name='手機號碼')),
                ('birthday', models.TextField(verbose_name='生日')),
            ],
        ),
    ]
