# Generated by Django 3.1 on 2023-06-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google_account_search',
            name='email',
            field=models.CharField(max_length=255, verbose_name='信箱'),
        ),
        migrations.AlterField(
            model_name='google_account_table',
            name='bakemail',
            field=models.CharField(max_length=255, verbose_name='備用信箱'),
        ),
        migrations.AlterField(
            model_name='google_account_table',
            name='birthday',
            field=models.CharField(max_length=255, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='google_account_table',
            name='email',
            field=models.CharField(max_length=255, verbose_name='信箱'),
        ),
        migrations.AlterField(
            model_name='google_account_table',
            name='password',
            field=models.CharField(max_length=255, verbose_name='密碼'),
        ),
        migrations.AlterField(
            model_name='google_account_table',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='手機號碼'),
        ),
    ]
