# Generated by Django 3.1 on 2023-06-04 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fourm_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, verbose_name='主題')),
                ('content', models.TextField(null=True, verbose_name='內容')),
                ('user_name', models.CharField(default='用戶不存在', max_length=100, verbose_name='用戶名')),
                ('fourm_name', models.CharField(default='把名不存在', max_length=100, verbose_name='把名')),
                ('publish_time', models.DateTimeField(default=datetime.datetime(2023, 6, 4, 19, 49, 50, 900852), verbose_name='發帖時間')),
            ],
        ),
        migrations.CreateModel(
            name='fourm_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, verbose_name='主題')),
                ('content', models.TextField(null=True, verbose_name='內容')),
                ('title_id', models.BigIntegerField(verbose_name='主題ID')),
                ('content_id', models.BigIntegerField(verbose_name='內容ID')),
                ('fourm_name', models.CharField(default='把名不存在', max_length=100, verbose_name='把名')),
                ('publish_time', models.DateTimeField(default=datetime.datetime(2023, 6, 4, 19, 49, 50, 901854), verbose_name='發帖時間')),
                ('choice_result', models.TextField(verbose_name='標籤')),
                ('sign', models.BigIntegerField(default='0', verbose_name='標記')),
            ],
        ),
    ]
